Plotter_settings:
  Output: 'output/plots/learning'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time']

Agent_settings:
  Output_csv: 'output/csv/learning'
  Output_model: 'output/models/learning'
  Environment:
    Gui: False
    Num_seconds: 100000
    Min_green: 5
    Max_green: 60
    Yellow_time: 3
    Delta_time: 5
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1
    QL_run_1:
      Agent_type: 'QL'
      Runs: 10
      Alpha: 0.5
      Gamma: 0.5
      Init_epsilon: 1.0
      Min_epsilon: 0.1
      Decay: 0.9
    QL_run_2:
      Agent_type: 'QL'
      Runs: 10
      Alpha: 0.7
      Gamma: 0.7
      Init_epsilon: 1.0
      Min_epsilon: 0.1
      Decay: 0.8
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 10
      Alpha: 0.00005
      Gamma: 0.5
      Epsilon: 0.01
      FourierOrder: 7
      Lambda: 0.999
    SARSA_run_2:
      Agent_type: 'SARSA'
      Runs: 10
      Alpha: 0.0001
      Gamma: 0.7
      Epsilon: 0.01
      FourierOrder: 5
      Lambda: 0.0999
      

